### ISSUE TITLE
Нарисовать дизайн главной страницы

### ISSUE THREAD

**Issue by jegius** [BsnTey/projectSM#3]
чтобы что-то делать нужно знать что ты делаешь, по этому нужно сейчас в фигме набросать базовый дизайн страницы со списком юзеров + токенов по юзерам

**Comment by BsnTey** [comment]
https://www.figma.com/file/heh6bZJgGjm3AjKgvHKUaE/Untitled?node-id=0%3A1&t=VQAbOprpHF4etYrn-1
