### ISSUE TITLE
Создать дизайн в фигме страницы авторизации

### ISSUE THREAD

**Issue by jegius** [BsnTey/projectSM#30]

**Comment by BsnTey** [comment]
https://www.figma.com/file/zXyL8yNlvl2nRYNJn8cvgJ/%D0%A1%D0%BF%D0%BE%D1%80%D1%82%D0%BC%D0%B0%D1%81%D1%82%D0%B5%D1%80-(Copy)?node-id=0-1&t=xADyts48g7jRfmvx-0
