### ISSUE TITLE
Сверстать страницу Личный кабинет

### ISSUE THREAD

**Issue by jegius** [BsnTey/projectSM#45]
Сверстать страницу "Личный кабинет"

**Comment by BsnTey** [comment]
https://www.figma.com/file/zXyL8yNlvl2nRYNJn8cvgJ/%D0%A1%D0%BF%D0%BE%D1%80%D1%82%D0%BC%D0%B0%D1%81%D1%82%D0%B5%D1%80-(Copy)?node-id=0%3A1&t=50CjV9IUdNDytx9h-1

макет личного кабинета и модальных окон восстановления пароля
